apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-registry-secret"
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" .Values.image }}